repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.4.0
  hooks:
  - id: trailing-whitespace
  - id: end-of-file-fixer
  - id: check-yaml
  - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.3.0
  hooks:
  - id: black
    files: \.py$
  - id: black-jupyter
    files: \.ipynb$
- repo: https://github.com/PyCQA/flake8
  rev: 5.0.4
  hooks:
  - id: flake8
    args: ['--ignore=E501']
    files: \.py$
- repo: https://github.com/nbQA-dev/nbQA
  rev: 1.5.3
  hooks:
  - id: nbqa-flake8
    files: \.ipynb$
    args: ['--ignore=E501,E402']
- repo: https://github.com/fastai/nbdev
  rev: 2.2.10
  hooks:
  - id: nbdev_clean
    files: \.ipynb$
    args: ['--fname', 'src']
