name: omniplot310
channels:
  - conda-forge
  - defaults
  - anaconda
  - bioconda
dependencies:
  - pip=22.3.1
  - python=3.10.9
  - setuptools
  - wheel
  - cython
  - pybigwig
  - pip:
    - git+https://github.com/koonimaru/omniplot.git
